"use client";

/**
 * /news — Daily Brief. V2 Ambient Futurism design.
 *
 * Single ranked list of up to 10 stories. Click to expand "Why it matters".
 * Category indicated by colored dot, not column.
 * Stories generated by Claude with live web search, cached per-user per-day.
 */

import { useEffect, useState } from "react";
import type { NewsBrief, NewsCategory, NewsStory } from "@/lib/news-brief";

// ─── Category config ──────────────────────────────────────────────────────────

type CatConfig = { label: string; color: string };

const CAT: Record<string, CatConfig> = {
  football:    { label: "Football",    color: "#F97316" },
  geopolitics: { label: "Geopolitics", color: "#FF8A8A" },
  business:    { label: "Business",    color: "#6FD49A" },
  tech:        { label: "Tech",        color: "#7EE7FF" },
  ai:          { label: "AI",          color: "#B388FF" },
  other:       { label: "Other",       color: "#6E6E86" },
};

// ─── Single story row ─────────────────────────────────────────────────────────

function StoryRow({ story, index }: { story: NewsStory; index: number }) {
  const [open, setOpen] = useState(false);
  const cfg = CAT[story.category] ?? CAT.other;

  // Parse hostname safely for display
  let hostname = "—";
  if (story.source) {
    try { hostname = new URL(story.source).hostname.replace("www.", ""); } catch { /* noop */ }
  }

  return (
    <div
      onClick={() => setOpen((v) => !v)}
      style={{
        padding: "14px 20px",
        borderBottom: "1px solid var(--line)",
        cursor: "pointer",
        background: open ? "rgba(179,136,255,0.035)" : "transparent",
        transition: "background 100ms",
      }}
    >
      {/* Row header */}
      <div style={{ display: "flex", alignItems: "flex-start", gap: 14 }}>
        {/* Rank */}
        <span style={{
          flexShrink: 0,
          fontFamily: "var(--f-mono)",
          fontSize: 10,
          color: "var(--ink-4)",
          letterSpacing: "0.08em",
          lineHeight: "20px",
          minWidth: 18,
          textAlign: "right",
        }}>
          {String(index + 1).padStart(2, "0")}
        </span>

        {/* Content */}
        <div style={{ flex: 1, minWidth: 0 }}>
          {/* Category dot + label */}
          <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 5 }}>
            <span style={{
              width: 5, height: 5, borderRadius: "50%",
              background: cfg.color,
              boxShadow: `0 0 5px ${cfg.color}`,
              flexShrink: 0,
            }} />
            <span style={{ fontSize: 9.5, fontWeight: 600, letterSpacing: "0.14em", textTransform: "uppercase", color: cfg.color }}>
              {cfg.label}
            </span>
          </div>

          {/* Headline */}
          <div style={{
            fontSize: 13.5,
            lineHeight: 1.42,
            letterSpacing: "-0.008em",
            color: "var(--ink)",
            textWrap: "pretty",
          } as React.CSSProperties}>
            {story.headline}
          </div>

          {/* Expanded: Why it matters */}
          {open && (
            <div style={{ marginTop: 12 }}>
              <div style={{ fontSize: 10, letterSpacing: "0.18em", textTransform: "uppercase", color: "var(--ink-3)", fontWeight: 600, marginBottom: 6 }}>
                Why it matters
              </div>
              <p style={{ fontSize: 12.5, lineHeight: 1.55, color: "var(--ink-2)", margin: "0 0 10px 0" }}>
                {story.whyItMatters || story.summary}
              </p>
              {story.source && (
                <a
                  href={story.source}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={(e) => e.stopPropagation()}
                  style={{ fontSize: 11, color: "var(--cyan)", display: "inline-flex", alignItems: "center", gap: 5, letterSpacing: "0.02em" }}
                >
                  Read source
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>
                    <polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/>
                  </svg>
                </a>
              )}
            </div>
          )}

          {/* Footer: source + chevron */}
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: open ? 10 : 7 }}>
            <span style={{ fontSize: 10, color: "var(--ink-4)", fontFamily: "var(--f-mono)", letterSpacing: "0.04em", textTransform: "uppercase" }}>
              {hostname}
            </span>
            <svg
              width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
              style={{ color: "var(--ink-4)", transform: open ? "rotate(180deg)" : "none", transition: "transform 0.15s", flexShrink: 0 }}
            >
              <polyline points="6 9 12 15 18 9"/>
            </svg>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Skeleton row ─────────────────────────────────────────────────────────────

function SkeletonRow({ index }: { index: number }) {
  return (
    <div style={{ padding: "14px 20px", borderBottom: "1px solid var(--line)", display: "flex", gap: 14 }}>
      <span style={{ fontFamily: "var(--f-mono)", fontSize: 10, color: "var(--ink-4)", letterSpacing: "0.08em", minWidth: 18, textAlign: "right", lineHeight: "20px", flexShrink: 0 }}>
        {String(index + 1).padStart(2, "0")}
      </span>
      <div style={{ flex: 1 }}>
        <div style={{ height: 8, width: 48, background: "rgba(255,255,255,0.07)", borderRadius: 4, marginBottom: 8 }} />
        <div style={{ height: 36, background: "rgba(255,255,255,0.04)", borderRadius: 6 }} />
      </div>
    </div>
  );
}

// ─── Main page ─────────────────────────────────────────────────────────────────

export default function NewsPage() {
  const [brief, setBrief]           = useState<NewsBrief | null>(null);
  const [loading, setLoading]       = useState(true);
  const [generating, setGenerating] = useState(false);

  const load = async () => {
    setLoading(true);
    const res = await fetch("/api/news/generate").catch(() => null);
    if (res?.ok) {
      const data = await res.json();
      if (data) setBrief(data);
    }
    setLoading(false);
  };

  const generate = async () => {
    setGenerating(true);
    const res = await fetch("/api/news/generate", { method: "POST" }).catch(() => null);
    if (res?.ok) {
      const data = await res.json();
      if (data) setBrief(data);
    }
    setGenerating(false);
  };

  useEffect(() => { load(); }, []);

  const now = new Date();
  const dayNames = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
  const monthNames = ["January","February","March","April","May","June","July","August","September","October","November","December"];
  const genTime = brief
    ? new Date(brief.generatedAt).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })
    : null;

  // Top 10 stories, preserving order (Claude ranks them by significance)
  const stories: NewsStory[] = (brief?.stories ?? []).slice(0, 10);

  return (
    <div style={{ maxWidth: 720, padding: "0 0 40px" }}>

      {/* Page title */}
      <div className="cc-pagetitle" style={{ marginBottom: 24 }}>
        <div>
          <h1>Daily <span className="grad-text">Brief</span>.</h1>
          <div className="sub">
            {dayNames[now.getDay()]}, {monthNames[now.getMonth()]} {now.getDate()}, {now.getFullYear()}
            {genTime ? ` · generated ${genTime}` : ""}
            {brief ? ` · ${stories.length} stories` : ""}
          </div>
        </div>
        <button
          className="cc-btn"
          onClick={generate}
          disabled={generating || loading}
          style={{ opacity: generating || loading ? 0.5 : 1 }}
        >
          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
            style={{ animation: generating ? "spin 1s linear infinite" : "none" }}>
            <polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/>
            <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/>
          </svg>
          {generating ? "Searching…" : "Refresh"}
        </button>
      </div>

      {/* Generating state */}
      {generating && (
        <div className="cc-card" style={{ padding: "48px 32px", textAlign: "center" }}>
          <div style={{ fontSize: 13, color: "var(--ink-2)", marginBottom: 8 }}>Searching the web…</div>
          <div style={{ fontSize: 12, color: "var(--ink-3)" }}>Claude is finding today&apos;s top stories</div>
        </div>
      )}

      {/* Story list */}
      {!generating && (
        <div className="cc-card" style={{ padding: 0, overflow: "hidden" }}>
          {loading ? (
            // Skeleton
            Array.from({ length: 10 }, (_, i) => <SkeletonRow key={i} index={i} />)
          ) : stories.length === 0 ? (
            <div style={{ padding: "48px 32px", textAlign: "center" }}>
              <div style={{ fontSize: 13, color: "var(--ink-2)", marginBottom: 16 }}>No brief generated yet for today.</div>
              <button className="cc-btn cc-btn-primary" onClick={generate} style={{ margin: "0 auto" }}>
                Generate Today&apos;s Brief
              </button>
              <div style={{ fontSize: 11, color: "var(--ink-4)", marginTop: 10 }}>~30s · Claude searches the web for real news</div>
            </div>
          ) : (
            stories.map((s, i) => <StoryRow key={i} story={s} index={i} />)
          )}
        </div>
      )}

      {/* Footer */}
      {brief && !loading && !generating && (
        <div style={{ marginTop: 20, color: "var(--ink-4)", fontSize: 11, letterSpacing: "0.04em", display: "flex", justifyContent: "space-between" }}>
          <span>Live web search · No editorial opinion</span>
          <span style={{ fontFamily: "var(--f-mono)", letterSpacing: "0.06em" }}>
            {now.getFullYear()}.{String(now.getMonth()+1).padStart(2,"0")}.{String(now.getDate()).padStart(2,"0")}
          </span>
        </div>
      )}

      <style>{`@keyframes spin{from{transform:rotate(0)}to{transform:rotate(360deg)}}`}</style>
    </div>
  );
}
