"use client";

/**
 * /news — Daily Brief. 4-column grid layout.
 *
 * Columns: Football | Geopolitics | Business | Tech & AI
 * 5 stories per column (20 total), generated by Claude with live web search.
 * Auto-generates on load if no brief exists for today.
 * Archive drawer shows last 30 days of saved briefs (DB-only reads).
 */

import { useEffect, useState, useCallback } from "react";
import type { NewsBrief, NewsStory } from "@/lib/news-brief";

// ─── Types ────────────────────────────────────────────────────────────────────

type ArchiveEntry = {
  date: string;
  storyCount: number;
  topHeadline: string;
  generatedAt: string;
};

// ─── Column config ────────────────────────────────────────────────────────────

const COLUMNS = [
  { id: "football",    label: "Football",    color: "#F97316", categories: ["football"] },
  { id: "geopolitics", label: "Geopolitics", color: "#FF8A8A", categories: ["geopolitics"] },
  { id: "business",    label: "Business",    color: "#6FD49A", categories: ["business"] },
  { id: "tech",        label: "Tech & AI",   color: "#64FFDA", categories: ["tech", "ai"] },
];

// ─── Story card ───────────────────────────────────────────────────────────────

function StoryCard({ story, accentColor }: { story: NewsStory; accentColor: string }) {
  const [open, setOpen] = useState(false);

  let hostname = "";
  if (story.source) {
    try { hostname = new URL(story.source).hostname.replace("www.", ""); } catch { /* noop */ }
  }

  // Prefer new `summary` field; fall back to deprecated `whyItMatters` for old rows
  const summaryText = story.summary || story.whyItMatters || "";
  const keyPoints: string[] = Array.isArray(story.keyPoints) ? story.keyPoints : [];

  return (
    <div
      onClick={() => setOpen((v) => !v)}
      style={{
        padding: "12px 0",
        borderBottom: "1px solid var(--line)",
        cursor: "pointer",
      }}
    >
      {/* Headline row */}
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 8 }}>
        <div style={{
          fontSize: 13,
          lineHeight: 1.42,
          letterSpacing: "-0.008em",
          color: "var(--ink)",
          flex: 1,
        } as React.CSSProperties}>
          {story.headline}
        </div>
        <svg
          width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
          style={{
            color: "var(--ink-4)",
            transform: open ? "rotate(180deg)" : "none",
            transition: "transform 0.15s",
            flexShrink: 0,
            marginTop: 3,
          }}
        >
          <polyline points="6 9 12 15 18 9"/>
        </svg>
      </div>

      {/* Source domain */}
      {hostname && (
        <div style={{
          fontSize: 10, color: "var(--ink-4)",
          fontFamily: "var(--f-mono)", letterSpacing: "0.04em",
          textTransform: "uppercase", marginTop: 5,
        }}>
          {hostname}
        </div>
      )}

      {/* Expanded: Summary + key points + source */}
      {open && (
        <div style={{ marginTop: 10 }}>
          {summaryText && (
            <p style={{ fontSize: 12.5, lineHeight: 1.6, color: "var(--ink-2)", margin: "0 0 10px 0" }}>
              {summaryText}
            </p>
          )}
          {keyPoints.length > 0 && (
            <ul style={{ margin: "0 0 10px 0", paddingLeft: 16 }}>
              {keyPoints.map((pt, i) => (
                <li key={i} style={{ fontSize: 12, lineHeight: 1.5, color: "var(--ink-3)", marginBottom: 3 }}>
                  {pt}
                </li>
              ))}
            </ul>
          )}
          {story.source && (
            <a
              href={story.source} target="_blank" rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
              style={{ fontSize: 11, color: accentColor, display: "inline-flex", alignItems: "center", gap: 5 }}
            >
              Read source
              <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>
                <polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/>
              </svg>
            </a>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Column skeleton ──────────────────────────────────────────────────────────

function ColumnSkeleton() {
  return (
    <>
      {Array.from({ length: 5 }, (_, i) => (
        <div key={i} style={{ padding: "12px 0", borderBottom: "1px solid var(--line)" }}>
          <div style={{ height: 13, background: "rgba(255,255,255,0.06)", borderRadius: 4, marginBottom: 6, width: "100%" }} />
          <div style={{ height: 13, background: "rgba(255,255,255,0.04)", borderRadius: 4, width: "70%" }} />
          <div style={{ height: 10, background: "rgba(255,255,255,0.03)", borderRadius: 3, width: "35%", marginTop: 8 }} />
        </div>
      ))}
    </>
  );
}

// ─── Archive drawer ───────────────────────────────────────────────────────────

function formatArchiveDate(dateStr: string): string {
  const d = new Date(dateStr + "T12:00:00");
  return d.toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short" });
}

function ArchiveDrawer({
  open, onClose, entries, loading, onSelectDate, selectedDate,
}: {
  open: boolean;
  onClose: () => void;
  entries: ArchiveEntry[];
  loading: boolean;
  onSelectDate: (date: string) => void;
  selectedDate: string | null;
}) {
  return (
    <>
      {/* Backdrop */}
      {open && (
        <div
          onClick={onClose}
          style={{
            position: "fixed", inset: 0,
            background: "rgba(0,0,0,0.4)",
            zIndex: 40,
            backdropFilter: "blur(2px)",
          }}
        />
      )}

      {/* Drawer panel */}
      <div style={{
        position: "fixed", top: 0, right: 0, bottom: 0,
        width: "min(320px, 90vw)",
        background: "#0d0d14",
        borderLeft: "1px solid var(--line)",
        zIndex: 41,
        transform: open ? "translateX(0)" : "translateX(100%)",
        transition: "transform 0.25s ease",
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
      }}>
        {/* Drawer header */}
        <div style={{
          padding: "16px 20px",
          borderBottom: "1px solid var(--line)",
          display: "flex", alignItems: "center", justifyContent: "space-between",
          flexShrink: 0,
        }}>
          <span style={{ fontSize: 12, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "var(--ink-2)" }}>
            Archive
          </span>
          <button
            onClick={onClose}
            style={{ background: "none", border: "none", cursor: "pointer", padding: 4, color: "var(--ink-4)" }}
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
            </svg>
          </button>
        </div>

        {/* Drawer list */}
        <div style={{ flex: 1, overflowY: "auto" }}>
          {loading ? (
            <div style={{ padding: "32px 20px", textAlign: "center", fontSize: 12, color: "var(--ink-4)" }}>
              Loading…
            </div>
          ) : entries.length === 0 ? (
            <div style={{ padding: "32px 20px", textAlign: "center", fontSize: 12, color: "var(--ink-4)" }}>
              No past briefs yet
            </div>
          ) : (
            entries.map(entry => {
              const isSelected = selectedDate === entry.date;
              return (
                <div
                  key={entry.date}
                  onClick={() => { onSelectDate(entry.date); onClose(); }}
                  style={{
                    padding: "12px 20px",
                    borderBottom: "1px solid var(--line)",
                    cursor: "pointer",
                    background: isSelected ? "rgba(124,92,255,0.08)" : "transparent",
                    transition: "background 100ms",
                  }}
                  onMouseEnter={e => { if (!isSelected) (e.currentTarget as HTMLDivElement).style.background = "rgba(255,255,255,0.03)"; }}
                  onMouseLeave={e => { if (!isSelected) (e.currentTarget as HTMLDivElement).style.background = "transparent"; }}
                >
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 4 }}>
                    <span style={{ fontSize: 12, fontWeight: 600, color: isSelected ? "#7C5CFF" : "var(--ink-2)", letterSpacing: "0.02em" }}>
                      {formatArchiveDate(entry.date)}
                    </span>
                    <span style={{ fontSize: 10, color: "var(--ink-4)", fontFamily: "var(--f-mono)" }}>
                      {entry.storyCount}
                    </span>
                  </div>
                  {entry.topHeadline && (
                    <div style={{
                      fontSize: 11.5, color: "var(--ink-3)", lineHeight: 1.4,
                      overflow: "hidden", display: "-webkit-box",
                      WebkitLineClamp: 2, WebkitBoxOrient: "vertical",
                    } as React.CSSProperties}>
                      {entry.topHeadline}
                    </div>
                  )}
                </div>
              );
            })
          )}
        </div>
      </div>
    </>
  );
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function NewsPage() {
  const [brief, setBrief]           = useState<NewsBrief | null>(null);
  const [loading, setLoading]       = useState(true);
  const [generating, setGenerating] = useState(false);
  const [confirmRefresh, setConfirmRefresh] = useState(false);

  // Archive state
  const [archiveOpen, setArchiveOpen]     = useState(false);
  const [archiveList, setArchiveList]     = useState<ArchiveEntry[]>([]);
  const [archiveLoading, setArchiveLoading] = useState(false);
  const [viewingDate, setViewingDate]     = useState<string | null>(null);
  const [viewingBrief, setViewingBrief]   = useState<NewsBrief | null>(null);
  const [viewingLoading, setViewingLoading] = useState(false);

  const generate = useCallback(async () => {
    setGenerating(true);
    setConfirmRefresh(false);
    const res = await fetch("/api/news/generate", { method: "POST" }).catch(() => null);
    if (res?.ok) {
      const data = await res.json();
      if (data) setBrief(data);
    }
    setGenerating(false);
  }, []);

  // Initial load: fetch today's brief; auto-generate if missing
  useEffect(() => {
    async function load() {
      const res = await fetch("/api/news/generate").catch(() => null);
      if (res?.ok) {
        const data = await res.json();
        if (data) {
          setBrief(data);
          setLoading(false);
        } else {
          setLoading(false);
          generate();
        }
      } else {
        setLoading(false);
      }
    }
    load();
  }, [generate]);

  // Load archive list when drawer opens
  useEffect(() => {
    if (!archiveOpen || archiveList.length > 0) return;
    setArchiveLoading(true);
    fetch("/api/news/archive")
      .then(r => r.json())
      .then(data => setArchiveList(Array.isArray(data) ? data : []))
      .catch(() => {})
      .finally(() => setArchiveLoading(false));
  }, [archiveOpen, archiveList.length]);

  // Load a specific date's brief
  async function loadDateBrief(date: string) {
    setViewingDate(date);
    setViewingBrief(null);
    setViewingLoading(true);
    const res = await fetch(`/api/news/archive?date=${date}`).catch(() => null);
    if (res?.ok) {
      const data = await res.json();
      setViewingBrief(data);
    }
    setViewingLoading(false);
  }

  function backToToday() {
    setViewingDate(null);
    setViewingBrief(null);
    setViewingLoading(false);
  }

  function handleRefreshClick() {
    if (!brief) { generate(); return; }
    const ageMs = Date.now() - new Date(brief.generatedAt).getTime();
    if (ageMs < 3600000) {
      setConfirmRefresh(true);
    } else {
      generate();
    }
  }

  // What to display in the grid
  const isViewingPast = viewingDate !== null;
  const displayedBrief = isViewingPast ? viewingBrief : brief;
  const displayedLoading = isViewingPast ? viewingLoading : loading;

  const now = new Date();
  const DAY_NAMES  = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
  const MONTH_NAMES = ["January","February","March","April","May","June","July","August","September","October","November","December"];

  const genTime = displayedBrief
    ? new Date(displayedBrief.generatedAt).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })
    : null;

  const columns = COLUMNS.map(col => ({
    ...col,
    stories: (displayedBrief?.stories ?? []).filter(s => col.categories.includes(s.category)),
  }));

  return (
    <div style={{ padding: "0 0 40px" }}>

      {/* Page title */}
      <div className="cc-pagetitle" style={{ marginBottom: 24 }}>
        <div>
          <h1>Daily <span className="grad-text">Brief</span>.</h1>
          <div className="sub">
            {DAY_NAMES[now.getDay()]}, {MONTH_NAMES[now.getMonth()]} {now.getDate()}, {now.getFullYear()}
            {genTime && !isViewingPast ? ` · generated ${genTime}` : ""}
            {displayedBrief ? ` · ${displayedBrief.stories.length} stories` : ""}
          </div>
        </div>

        {/* Header actions */}
        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          {/* Archive button */}
          <button
            className="cc-btn"
            onClick={() => setArchiveOpen(true)}
            style={{ gap: 6 }}
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="21 8 21 21 3 21 3 8"/><rect x="1" y="3" width="22" height="5"/><line x1="10" y1="12" x2="14" y2="12"/>
            </svg>
            Archive
          </button>

          {/* Refresh button — hidden when viewing a past date */}
          {!isViewingPast && (
            <button
              className="cc-btn"
              onClick={handleRefreshClick}
              disabled={generating || loading}
              style={{ opacity: generating || loading ? 0.5 : 1 }}
            >
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
                style={{ animation: generating ? "spin 1s linear infinite" : "none" }}>
                <polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/>
                <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/>
              </svg>
              {generating ? "Searching…" : "Refresh"}
            </button>
          )}
        </div>
      </div>

      {/* 1-hour refresh confirmation */}
      {confirmRefresh && (
        <div style={{
          marginBottom: 16, padding: "12px 16px",
          background: "rgba(255,255,255,0.04)",
          border: "1px solid var(--line)",
          borderRadius: 10,
          display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12,
        }}>
          <span style={{ fontSize: 12, color: "var(--ink-2)" }}>
            Today&apos;s brief is fresh, generated at {genTime}. Refresh anyway?
          </span>
          <div style={{ display: "flex", gap: 8, flexShrink: 0 }}>
            <button
              onClick={() => setConfirmRefresh(false)}
              style={{ fontSize: 11, color: "var(--ink-4)", background: "none", border: "none", cursor: "pointer", padding: "4px 8px" }}
            >
              Cancel
            </button>
            <button
              className="cc-btn cc-btn-primary"
              onClick={generate}
              style={{ fontSize: 11, padding: "4px 12px" }}
            >
              Refresh
            </button>
          </div>
        </div>
      )}

      {/* Viewing past date banner */}
      {isViewingPast && (
        <div style={{
          marginBottom: 16, padding: "10px 16px",
          background: "rgba(124,92,255,0.08)",
          border: "1px solid rgba(124,92,255,0.2)",
          borderRadius: 10,
          display: "flex", alignItems: "center", justifyContent: "space-between",
        }}>
          <span style={{ fontSize: 12, color: "var(--ink-2)" }}>
            Viewing: {formatArchiveDate(viewingDate!)}
          </span>
          <button
            onClick={backToToday}
            style={{ fontSize: 11, color: "#7C5CFF", background: "none", border: "none", cursor: "pointer", display: "flex", alignItems: "center", gap: 5 }}
          >
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="15 18 9 12 15 6"/>
            </svg>
            Back to today
          </button>
        </div>
      )}

      {/* Generating state */}
      {generating && (
        <div className="cc-card" style={{ padding: "48px 32px", textAlign: "center" }}>
          <div style={{ fontSize: 13, color: "var(--ink-2)", marginBottom: 8 }}>Searching the web…</div>
          <div style={{ fontSize: 12, color: "var(--ink-3)" }}>Claude is finding today&apos;s top stories</div>
        </div>
      )}

      {/* 4-column grid */}
      {!generating && (
        <div className="news-grid">
          {columns.map(col => (
            <div key={col.id} className="cc-card" style={{ padding: 0, overflow: "hidden" }}>
              {/* Column header */}
              <div style={{
                padding: "12px 16px",
                borderBottom: "1px solid var(--line)",
                display: "flex", alignItems: "center", gap: 8,
              }}>
                <span style={{
                  width: 6, height: 6, borderRadius: "50%",
                  background: col.color, boxShadow: `0 0 6px ${col.color}`,
                  flexShrink: 0,
                }} />
                <span style={{
                  fontSize: 10, fontWeight: 700,
                  letterSpacing: "0.14em", textTransform: "uppercase",
                  color: col.color, flex: 1,
                }}>
                  {col.label}
                </span>
                {!displayedLoading && (
                  <span style={{ fontSize: 10, color: "var(--ink-4)", fontFamily: "var(--f-mono)" }}>
                    {col.stories.length}
                  </span>
                )}
              </div>

              {/* Stories */}
              <div style={{ padding: "0 16px" }}>
                {displayedLoading ? (
                  <ColumnSkeleton />
                ) : col.stories.length === 0 ? (
                  <div style={{ padding: "24px 0", textAlign: "center", fontSize: 11, color: "var(--ink-4)" }}>
                    No stories
                  </div>
                ) : (
                  col.stories.map((s, i) => (
                    <StoryCard key={i} story={s} accentColor={col.color} />
                  ))
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Footer */}
      {displayedBrief && !displayedLoading && !generating && (
        <div style={{
          marginTop: 20, color: "var(--ink-4)", fontSize: 11,
          letterSpacing: "0.04em", display: "flex", justifyContent: "space-between",
        }}>
          <span>Live web search · No editorial opinion</span>
          <span style={{ fontFamily: "var(--f-mono)", letterSpacing: "0.06em" }}>
            {now.getFullYear()}.{String(now.getMonth()+1).padStart(2,"0")}.{String(now.getDate()).padStart(2,"0")}
          </span>
        </div>
      )}

      {/* Archive drawer */}
      <ArchiveDrawer
        open={archiveOpen}
        onClose={() => setArchiveOpen(false)}
        entries={archiveList}
        loading={archiveLoading}
        onSelectDate={loadDateBrief}
        selectedDate={viewingDate}
      />

      <style>{`
        @keyframes spin { from { transform: rotate(0) } to { transform: rotate(360deg) } }
        .news-grid {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 12px;
        }
        @media (max-width: 1024px) {
          .news-grid { grid-template-columns: repeat(2, 1fr); }
        }
        @media (max-width: 600px) {
          .news-grid { grid-template-columns: 1fr; }
        }
      `}</style>
    </div>
  );
}
