"use client";

/**
 * /news — Daily news brief page.
 * Shows today's brief (generated by Claude) or triggers generation.
 * Stories are categorized and each includes a "Why it matters" section.
 */

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Newspaper, RefreshCw, ChevronDown, ChevronUp } from "lucide-react";
import type { NewsBrief, NewsStory } from "@/lib/news-brief";

const CATEGORY_CONFIG: Record<string, { label: string; color: string; icon: string }> = {
  football:    { label: "Football",    color: "var(--workout-color)", icon: "⚽" },
  geopolitics: { label: "Geopolitics", color: "var(--red)",           icon: "🌍" },
  business:    { label: "Business",    color: "var(--calendar-color)",icon: "📈" },
  tech:        { label: "Tech",        color: "var(--news-color)",    icon: "💻" },
  ai:          { label: "AI",          color: "var(--library-color)", icon: "🤖" },
  other:       { label: "News",        color: "var(--text-secondary)","icon": "📰" },
};

function StoryCard({ story }: { story: NewsStory }) {
  const [expanded, setExpanded] = useState(false);
  const cfg = CATEGORY_CONFIG[story.category] ?? CATEGORY_CONFIG.other;

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      className="glass rounded-2xl p-5 cursor-pointer"
      onClick={() => setExpanded((v) => !v)}
      style={{ borderLeft: `3px solid ${cfg.color}` }}
    >
      {/* Category tag */}
      <div className="flex items-center justify-between mb-3">
        <span
          className="text-[11px] font-semibold uppercase tracking-wider px-2 py-0.5 rounded-full"
          style={{ background: `${cfg.color}18`, color: cfg.color }}
        >
          {cfg.icon} {cfg.label}
        </span>
        {expanded ? (
          <ChevronUp size={14} style={{ color: "var(--text-muted)" }} />
        ) : (
          <ChevronDown size={14} style={{ color: "var(--text-muted)" }} />
        )}
      </div>

      {/* Headline */}
      <h3 className="font-semibold text-base leading-snug mb-2" style={{ color: "var(--text-primary)" }}>
        {story.headline}
      </h3>

      {/* Summary */}
      <p className="text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>
        {story.summary}
      </p>

      {/* Why it matters (expandable) */}
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            style={{ overflow: "hidden" }}
          >
            <div
              className="mt-4 rounded-xl p-3"
              style={{ background: "var(--bg-elevated)" }}
            >
              <span className="text-xs font-semibold" style={{ color: cfg.color }}>
                Why it matters
              </span>
              <p className="text-sm mt-1 leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                {story.whyItMatters}
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function NewsPage() {
  const [brief, setBrief] = useState<NewsBrief | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const load = async () => {
    const res = await fetch("/api/news/generate");
    const data = await res.json();
    setBrief(data);
    setLoading(false);
  };

  const generate = async () => {
    setGenerating(true);
    const res = await fetch("/api/news/generate", { method: "POST" });
    const data = await res.json();
    setBrief(data);
    setGenerating(false);
  };

  useEffect(() => { load(); }, []);

  const today = new Date().toLocaleDateString("en-GB", {
    weekday: "long", day: "numeric", month: "long", year: "numeric",
  });

  return (
    <div className="page-enter p-5 md:p-10 max-w-2xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight" style={{ color: "var(--text-primary)" }}>
            Daily Brief
          </h1>
          <p className="text-sm mt-0.5" style={{ color: "var(--text-muted)" }}>{today}</p>
        </div>
        <button
          onClick={generate}
          disabled={generating}
          className="flex items-center gap-2 px-3 py-2 rounded-xl text-sm transition-all"
          style={{
            background: "var(--accent-dim)",
            color: "var(--accent-bright)",
            border: "1px solid var(--border-accent)",
          }}
        >
          <RefreshCw size={14} className={generating ? "animate-spin" : ""} />
          {generating ? "Generating…" : "Refresh"}
        </button>
      </div>

      {/* Loading state */}
      {loading && (
        <div className="space-y-3">
          {[1, 2, 3, 4].map((i) => (
            <div key={i} className="glass rounded-2xl h-28 animate-pulse" />
          ))}
        </div>
      )}

      {/* No brief yet */}
      {!loading && !brief && (
        <div className="glass rounded-2xl p-10 flex flex-col items-center gap-4">
          <Newspaper size={40} style={{ color: "var(--text-muted)" }} />
          <p style={{ color: "var(--text-secondary)" }}>No brief generated yet for today.</p>
          <button
            onClick={generate}
            disabled={generating}
            className="px-5 py-2.5 rounded-xl text-sm font-semibold"
            style={{ background: "var(--accent)", color: "#fff" }}
          >
            {generating ? "Generating…" : "Generate Today's Brief"}
          </button>
        </div>
      )}

      {/* Stories */}
      {brief && (
        <div className="space-y-3">
          {brief.stories.map((story, i) => (
            <StoryCard key={i} story={story} />
          ))}
          <p className="text-xs text-center pt-2" style={{ color: "var(--text-muted)" }}>
            Generated by Claude · Unbiased · {brief.stories.length} stories
          </p>
        </div>
      )}
    </div>
  );
}
