import json
defs = json.load(open('acc_definitions.json'))
corr = json.load(open('acc_corrections.json'))
BD={}; BC=[]
def D(i,t): BD[str(i)]=t
def C(wid,lang,word,old,new,issue,conf):
    BC.append({"word_id":str(wid),"language_code":lang,"word":word,
        "field":f"translations.{lang}" if lang else "definition",
        "old_value":old,"new_value":new,"issue":issue,"confidence":conf})

D(3301,"to dress yourself in a piece of clothing")
D(3302,"to learn something you did not know")
D(3303,"to admit that you did something wrong")
D(3304,"to have the same opinion as someone")
D(3305,"to go and look at something new")
D(3306,"to remove a piece of clothing")
D(3307,"to enter a place")
D(3308,"to leave home for an activity")
D(3309,"to continue doing something")
D(3310,"to perform or complete a task")
D(3311,"to rise from bed")
D(3312,"to arrive at a place")
D(3313,"to be found or appear unexpectedly")
D(3314,"to go to bed")
D(3315,"to react with sudden fear or panic")
D(3316,"spoiled or done badly")
D(3317,"seriously mentally ill")
D(3318,"very silly or unreasonable")
D(3319,"untidy and dirty")
D(3320,"badly ruined or in a bad state")
D(3321,"alone; without help")
D(3322,"very strange and unusual")
D(3323,"tending to argue or challenge others")
D(3324,"to face a problem or fear directly")
D(3325,"to suddenly leave or abandon someone")
D(3326,"beginning to cry")
D(3327,"to move past a slower vehicle")
D(3328,"to do or use too much of something")
D(3329,"far more than is needed")
D(3330,"to succeed in dealing with a difficulty")
D(3331,"to think of an idea or plan")
D(3332,"confused and unable to understand")
D(3333,"to consider something carefully")
D(3334,"to find your way across a place")
D(3335,"very stupid or foolish")
D(3336,"to suddenly attack or oppose someone")
D(3337,"to keep going through a hard time")
D(3338,"to set off on a journey")
D(3339,"to stay calm and in control")
D(3340,"to recover from something upsetting")
D(3341,"to regain calm and self-control")
D(3342,"to disappoint someone")
D(3343,"to stop working properly")
D(3344,"to end a relationship")
D(3345,"to care for a child until grown")
D(3346,"to remove a piece of clothing")
D(3347,"to take control of something")
D(3348,"to exercise to stay fit")
D(3349,"to solve or understand something")
D(3350,"to go and look at something new")
D(3351,"to continue doing something")
D(3352,"to cancel a planned event")
D(3353,"to tolerate something unpleasant")
D(3354,"to find something by chance")
D(3355,"to take care of someone or something")
D(3356,"to feel happy about something coming")
D(3357,"to remove a part by cutting")
D(3358,"to stop trying to do something")
D(3359,"to experience a difficult time")
D(3360,"to meet someone by chance")
D(3361,"to learn something you did not know")
D(3362,"to invent a story or excuse")
D(3363,"to refuse an offer or request")
D(3364,"to become less upset or excited")
D(3365,"to relax and stop worrying")
D(3366,"to take action to handle something")
D(3367,"to organise or resolve something")
D(3368,"to put equipment in place ready to use")
D(3369,"to have a friendly relationship")
D(3370,"to begin or proceed with something")
D(3371,"to leave one thing and start another")
D(3372,"to display something proudly to impress")
D(3373,"to look after someone or something")
D(3374,"to draw attention to something")
D(3375,"to see or hear something with difficulty")
D(3376,"to break into pieces")
D(3377,"to explode")
D(3378,"to meet socially")
D(3379,"to delay something to a later time")
D(3380,"to reach the same level as others")
D(3381,"to depend on someone for help")
D(3382,"to continue happening")
D(3383,"to move at the same speed as another")
D(3384,"to spend time relaxing with others")
D(3385,"to lose consciousness")
D(3386,"to collect something or someone")
D(3387,"to criticise and make someone feel small")
D(3388,"to dress yourself in a piece of clothing")
D(3389,"to use up all of something")
D(3390,"to make a bad mistake")
D(3391,"to close down permanently")
D(3392,"to be easily noticed among others")
D(3393,"to stay in a place a while longer")
D(3394,"to withdraw something you said")
D(3395,"to knock down a building")
D(3396,"to put on clothing to see if it fits")
D(3397,"to stop a device from working")
D(3398,"to stop sleeping")
D(3399,"to spend effort improving something")
D(3400,"to succeed despite difficulty")
D(3401,"to fail to keep up with others")
D(3402,"to manage with what you have")
D(3403,"to make contact with someone")
D(3404,"to remember the past")
D(3405,"to share your feelings honestly")
D(3406,"to speak more loudly")
D(3407,"to consider something carefully")
D(3408,"to be careful of danger")
D(3409,"to record something in writing")

C(3301,"de","put on","aufsetzen","anziehen","'aufsetzen' is for a hat; putting on a coat is 'anziehen'","medium")
C(3301,"fr","put on","mettez","mettre","the imperative was given; the base form is 'mettre'","low")
C(3306,"fr","take off","décoller","enlever","'décoller' is for an aeroplane; taking off shoes is 'enlever'","high")
C(3306,"it","take off","decollare","togliersi","'decollare' is for an aeroplane; taking off shoes is 'togliersi'","high")
C(3307,"es","come in","Entrar","entrar","the value was capitalised; the word is 'entrar'","low")
C(3307,"fr","come in","Entrez","entrer","the imperative was given; the base form is 'entrer'","low")
C(3313,"fr","turn up","venez","réapparaître","'venez' is the imperative 'come'; to turn up/appear is 'réapparaître'","medium")
C(3317,"it","insane","mentalmente instabile","folle","the value was a phrase; insane is 'folle'","low")
C(3326,"es","tearing up","llorisquear","lagrimear","'llorisquear' means to whimper; eyes tearing up is 'lagrimear'","medium")
C(3326,"de","tearing up","zerreißen","feuchte Augen bekommen","'zerreißen' means to rip apart; eyes tearing up is 'feuchte Augen bekommen'","medium")
C(3335,"it","dumb","muto","stupido","'muto' means mute/unable to speak; dumb (stupid) is 'stupido'","high")
C(3343,"de","break down","zusammenbrechen","eine Panne haben","'zusammenbrechen' means to collapse; a car breaking down is 'eine Panne haben'","medium")
C(3343,"fr","break down","panne","tomber en panne","'panne' is the noun; to break down is 'tomber en panne'","medium")
C(3343,"it","break down","scoppiare in lacrime","guastarsi","'scoppiare in lacrime' means to burst into tears; a car breaking down is 'guastarsi'","high")
C(3344,"de","break up","beenden","sich trennen","'beenden' means to end something; to break up (as a couple) is 'sich trennen'","medium")
C(3344,"it","break up","rompere","lasciarsi","'rompere' means to break an object; a couple breaking up is 'lasciarsi'","medium")
C(3345,"fr","bring up","faire monter","élever","'faire monter' means to carry up; to bring up a child is 'élever'","high")
C(3345,"it","bring up","crescere / educare","crescere","the value held two options; to bring up a child is 'crescere'","low")
C(3346,"fr","take off","décoller","enlever","'décoller' is for an aeroplane; taking off shoes is 'enlever'","high")
C(3346,"it","take off","decollare","togliersi","'decollare' is for an aeroplane; taking off shoes is 'togliersi'","high")
C(3348,"fr","work out","entraînement","s'entraîner","'entraînement' is the noun; to work out is 's'entraîner'","medium")
C(3362,"es","make up","constituir","inventar","'constituir' means to compose; to make up a reason is 'inventar'","high")
C(3362,"fr","make up","se maquiller","inventer","'se maquiller' means to put on makeup; to make up a reason is 'inventer'","high")
C(3372,"it","show off","esibire","vantarsi","'esibire' means to display something; to show off is 'vantarsi'","medium")
C(3375,"fr","make out","s'embrasser","distinguer","'s'embrasser' means to kiss; to make out/discern words is 'distinguer'","high")
C(3377,"de","blow up","sprengen","explodieren","'sprengen' means to blow something up; the building blowing up is 'explodieren'","low")
C(3383,"de","keep up","weitermachen","mithalten","'weitermachen' means to continue; to keep up with someone is 'mithalten'","medium")
C(3387,"es","put down","apoyar","menospreciar","'apoyar' means to support; to put someone down is 'menospreciar'","high")
C(3387,"de","put down","ablegen","herabsetzen","'ablegen' means to set an object down; to belittle someone is 'herabsetzen'","medium")
C(3387,"fr","put down","déposer","rabaisser","'déposer' means to set an object down; to belittle someone is 'rabaisser'","medium")
C(3387,"it","put down","mettere giù","sminuire","'mettere giù' means to set an object down; to belittle someone is 'sminuire'","medium")
C(3388,"de","put on","aufsetzen","anziehen","'aufsetzen' is for a hat; putting on a coat is 'anziehen'","medium")
C(3388,"fr","put on","mettez","mettre","the imperative was given; the base form is 'mettre'","low")
C(3409,"fr","write down","écrire","noter","'écrire' means to write; to write down/note is 'noter'","medium")
C(3409,"it","write down","annotare / prendere nota","annotare","the value held two options; to write down is 'annotare'","low")

defs.update(BD); corr.extend(BC)
json.dump(defs, open('acc_definitions.json','w'), ensure_ascii=False, indent=1)
json.dump(corr, open('acc_corrections.json','w'), ensure_ascii=False, indent=1)
print("batch defs:", len(BD), "batch corr:", len(BC), "| total defs:", len(defs), "total corr:", len(corr))
